#    基本语法
#        ● 大小写敏感
#        ● 使用缩进表示层级关系，k: v，使用空格分割k,v
#        ● 缩进时不允许使用Tab键，只允许使用空格。换行
#        ● 缩进的空格数目不重要，只要相同层级的元素左侧对齐即可
#        ● # 表示注释，从这个字符一直到行尾，都会被解析器忽略。
#
#        支持的写法：
#        ● 对象：键值对的集合，如：映射（map）/ 哈希（hash） / 字典（dictionary）
#        ● 数组：一组按次序排列的值，如：序列（sequence） / 列表（list）
#        ● 纯量：单个的、不可再分的值，如：字符串、数字、bool、日期


pig:
  age: 2
  id: 1
  name: 程莉茹

sheep:
  id: 1
  name: 肖恩
  age: 5

server:
  port: 8080