person:
  name: 张三
  age: 18
  birth-day: 2010/10/10 12:12:12
  like: true
  child: #嵌套对象
    name: 李四
    age: 20
    birth-day: 2018/10/10
    #text: ["abc","def"]
    text:
      - abc
      - def
  dogs: #List、数组
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  cats: #Map
    c1:
      name: 小蓝
      age: 3
    c2: {name: 小绿,age: 2} #对象也可用{}表示